#!/bin/bash

# Alias for extended git cleanup
if [[ -z $(git config --global alias.cleanup) ]] then;
    echo 'setting `git alias.cleanup` for cleaning up unreacheable branches in origin remote';
    git config --global alias.cleanup '!git remote prune origin && git branch -vv | grep origin | grep gone | awk '"'"'{print $1}'"'"' | xargs -L 1 git branch -df';
fi;

# Alias for extended git rebase-master
if [[ -z $(git config --global alias.rebase-master) ]] then;
    echo 'setting `git alias.rebase-master` for rebase w/ master';
    git config --global alias.rebase-master '!branch=$(git rev-parse --abbrev-ref HEAD)
        git checkout master && git pull && git checkout $branch && git rebase master';
fi;

# Alias for extended git merge-master
if [[ -z $(git config --global alias.merge-master) ]] then;
    echo 'setting `git alias.merge-master` for merge w/ master';
    git config --global alias.merge-master '!branch=$(git rev-parse --abbrev-ref HEAD)
        git checkout master && git pull && git checkout $branch && git merge master';
fi;

# Alias for extended git log
if [[ -z $(git config --global alias.xlog) ]] then;
    echo 'setting `git alias.xlog` for extended log';
    git config --global alias.xlog 'log --all --decorate --oneline --graph';
fi;

# Alias for first push upstream
if [[ -z $(git config --global alias.upush) ]] then;
    echo 'setting `git alias.upush` for upstream push into origin';
    git config --global alias.upush '!git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)'
fi;