#!/bin/bash

function git-branch-cleanup() {
    git remote prune origin && \
        git branch -vv | grep origin | grep gone | awk '{print $1}' | xargs -L 1 git branch -df
}

function git-rebase-with-master() {
    branch=${1:-$(git rev-parse --abbrev-ref HEAD)}
    echo "rebasing master on $branch"
    git checkout master && \
        git pull && \
        git checkout $branch && \
        git rebase master
}

if [[ -z $(git config --global alias.xlog) ]] then;
    echo 'setting git alias.xlog';
    git config --global alias.xlog 'log --all --decorate --oneline --graph';
fi;