#!/bin/bash

function git-branch-cleanup() {
    git remote prune origin && \
        git branch -vv | grep origin | grep gone | awk '{print $1}' | xargs -L 1 git branch -df
}

function git-rebase-with-master() {
    branch=${1:-$(git rev-parse --abbrev-ref HEAD)}
    echo "rebasing master on $branch"
    git checkout master && \
        git pull && \
        git checkout $branch && \
        git rebase master
}

# Alias for extended git log
if [[ -z $(git config --global alias.xlog) ]] then;
    echo 'setting `git alias.xlog` for extended log';
    git config --global alias.xlog 'log --all --decorate --oneline --graph';
fi;

# Alias for first push upstream
if [[ -z $(git config --global alias.pushu) ]] then;
    echo 'setting `git alias.pushu` for upstream push into origin';
    git config --global alias.pushu '!git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)'
fi;